apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecret.name }} 
  namespace: {{ .Values.externalsecret.namespace }} 
spec:
  refreshInterval: '0'
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clustersecretstore.name }} 
  target:
    name: postgres-secrets-manager
    creationPolicy: Owner
  data:
  {{- range .Values.items }}
  - secretKey: {{ .secretkey }}
    remoteRef:
      key: {{ .secretname }}
      property: {{ .property }}
   {{- end }}   
  